
workflows:
  maui-ios-build:
    name: Build and Deploy MAUI iOS App
    environment:
      xcode: latest
      vars:
        DOTNET_VERSION: 8.0.301
    scripts:
      - name: Install .NET SDK
        script: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh -v $DOTNET_VERSION
      - name: Print dotnet version (for debugging)
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet --version
      - name: Install MAUI workload
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet workload install maui
      - name: Restore dependencies
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet restore
      - name: Build iOS app
        script: |
          export PATH="$HOME/.dotnet:$PATH"
          dotnet publish -f net8.0-ios -c Release
    artifacts:
      - '**/bin/Release/**/*.ipa'
