workflows:
  maui-ios-build:
    name: Build iOS .NET MAUI App
    max_build_duration: 60
    environment:
      vars:
        DOTNET_VERSION: "8.0.x"
      xcode: latest
    scripts:
      - name: Install .NET SDK
        script: |
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$DOTNET_ROOT:$PATH
          curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel $DOTNET_VERSION
      - name: Restore dependencies
        script: dotnet restore
      - name: Build for iOS
        script: |
          dotnet build YourAppName.sln -c Release -f:net8.0-ios /p:Platform=iPhone
    artifacts:
      - build/ios/**/*.ipa
    publishing:
      email:
        recipients:
          - jordy.moorman@gmail.com
