# ==========================================================
# Bible Quest iOS Build — Codemagic Workflow
#
# Default mode ships to TestFlight. When you're ready for the
# App Store, flip the two flags under `publishing.app_store_connect`:
#   submit_to_testflight: false
#   submit_to_app_store: true
# ==========================================================

workflows:
  bible-quest-ios:
    name: Bible Quest for Kids – iOS Build (.NET MAUI)
    max_build_duration: 60
    environment:
      xcode: latest
      cocoapods: default
      node: 18.16.0
      vars:
        DOTNET_ROOT: /usr/local/share/dotnet
        APP_IDENTIFIER: $BUNDLE_ID
        TEAM_ID: $TEAM_ID
      groups:
        - ios_signing             # CERTIFICATE_*, PROVISIONING_PROFILE, KEYCHAIN_PASSWORD
        - app_store_connect       # APP_STORE_CONNECT_* variables
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install .NET SDK
        script: |
          set -euo pipefail
          brew install --cask dotnet-sdk
          export PATH="$DOTNET_ROOT:$PATH"
          dotnet --version
      - name: Build bundled web assets (npm)
        script: |
          cd BibleQuestForKids/wwwroot
          npm ci
          npm run build
      - name: Restore & publish MAUI iOS app
        script: |
          set -euo pipefail
          export PATH="$DOTNET_ROOT:$PATH"
          dotnet restore BibleQuestForKids/BibleQuestForKids.csproj
          dotnet publish BibleQuestForKids/BibleQuestForKids.csproj \
            -c Release \
            -f net8.0-ios \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:ArchiveOnBuild=true \
            -p:CreatePackage=true
      - name: Collect IPA
        script: |
          mkdir -p output
          find BibleQuestForKids/bin/Release/net8.0-ios/ios-arm64/publish -name '*.ipa' \
            -exec cp {} output/ \;
    artifacts:
      - output/*.ipa
    publishing:
      app_store_connect:
        auth: api_key
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_KEY
        submit_to_testflight: true
        submit_to_app_store: false
