workflows:
  ios-release:
    name: Bible Quest for Kids (iOS)
    integrations:
      app_store_connect:
        # This tells Codemagic to use the configured App Store Connect integration.
        # You must configure this under your Codemagic UI -> App Settings -> Integrations.
        # Make sure your key (p8), issuer ID, and key ID are added there.
        auth: integration

    environment:
      vars:
        DOTNET_VERSION: 8.0.301
        APP_IDENTIFIER: app.biblequest
        APP_DISPLAY_VERSION: 1.1.0
      xcode: latest
      node: latest

    scripts:
      - name: Install MAUI workloads
        script: |
          dotnet workload install maui-ios
          dotnet restore BibleQuestForKids/BibleQuestForKids.csproj

      - name: Build iOS app
        script: |
          dotnet publish BibleQuestForKids/BibleQuestForKids.csproj \
            -c Release \
            -f net8.0-ios \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:BuildIpa=true \
            -p:ApplicationId=$APP_IDENTIFIER \
            -p:ApplicationDisplayVersion=$APP_DISPLAY_VERSION \
            -p:ApplicationVersion=$(date +%s)

    artifacts:
      - BibleQuestForKids/bin/Release/net8.0-ios/ios-arm64/publish/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true