workflows:
  ios-release:
    name: BibleQuest iOS Release
    environment:
      vars:
        BUNDLE_ID: app.biblequest
        TEAM_ID: 2989BXM365
      xcode: latest
    integrations:
      app_store_connect: appstore_credentials

    signing:
      ios:
        certificates:
          - Jordy Moorman Distribution
        provisioning_profiles:
          - BibleQuest_AppStore_Distribution_ProvProfile

    scripts:
      - name: Install .NET MAUI
        script: |
          dotnet workload install maui

      - name: Restore and Build
        script: |
          dotnet restore BibleQuestForKids/BibleQuestForKids.csproj
          dotnet build BibleQuestForKids/BibleQuestForKids.csproj -c Release -f net8.0-ios

      - name: Publish IPA
        script: |
          dotnet publish BibleQuestForKids/BibleQuestForKids.csproj \
            -c Release \
            -f net8.0-ios \
            -p:RuntimeIdentifier=ios-arm64 \
            -p:BuildIpa=true \
            -p:ApplicationId=$BUNDLE_ID \
            -p:CodesignKey="iPhone Distribution: Jordy Moorman ($TEAM_ID)" \
            -p:CodesignProvision="BibleQuest_AppStore_Distribution_ProvProfile" \
            -p:TeamId=$TEAM_ID

    artifacts:
      - BibleQuestForKids/bin/Release/net8.0-ios/ios-arm64/publish/*.ipa

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true